version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Europe/Madrid"
    labels:
      - "dependency"
    assignees:
      - "AlvarX4z"
    commit-message:
      prefix: "DEPENDENCY: "
