services:
  postgresql:
    image: postgres:16.4
    container_name: PostgreSQL
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: media_library
