spring:
  application:
    name: Media Library
  datasource:
    url: jdbc:h2:mem:media_library;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    driver-class-name: org.h2.Driver
    username: user
    password: pass
  h2:
    console:
      enabled: true
      path: /db
      settings.trace: false
      settings.web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: dev
  sql:
    init:
      data-locations: classpath:database/import_*.sql
